version: "3"
services:
  back:
    image: yt8492/snorlax:latest
    container_name: "snorlax-back"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_URL: ${S3_URL}
  front:
    image: yt8492/snorlax-front:latest
    container_name: "snorlax-front"
    ports:
      - "8080:80"